### ISSUE TITLE
Multiple Much needed Feature Requests & Fix

### ISSUE THREAD

**Issue by Yuzi1221** [AscensionGameDev/Intersect-Engine#1029]
**Is your feature request related to a problem? Please describe.**
4D Movement is limiting to fast or diverse gameplay,
Movement speed is limited not sure why beyond 60 does no changes,

**Describe the solution you'd like**
We would like an option for 8D movement not just 4D,
Fix Speed Limit,
Add weather mechanics,
Add Mouse point and click spells that cast towards mouse and or lock on to target.

**Additional content**
Needs Weather Mechanics,
Needs Mouse point and click spells that cast towards mouse and or lock on to target.

**Comment by dudevelopement** [comment]
Moving in 8 directions would be nice to have in the engine and be optional to activate.
Spells with mouse click that will define where the spell will be born I also find it interesting, but I don't know if it goes for that in the engine.

**Comment by Cheshire92** [comment]
Could this be split into separate issues please?
Easier to track since it's multiple requests.

**Comment by Arufonsu** [comment]
Something related to weather has already been requested in another issue report.
8D Movement has been a hot topic for a long time, but it seems to be out of the current plans right now.
As for speed limit, you may want to be more specific about this one, and open an issue report for it's own topic, same with the mouse/cursor ones.
Closing this for now since there's been no answer from this issue report's author for over a month.
