### ISSUE TITLE
Load the last map edited by the user when loading into the editor

### ISSUE THREAD

**Issue by Cheshire92** [AscensionGameDev/Intersect-Engine#1049]
**Is your feature request related to a problem? Please describe.**
Currently, the map editor always loads the first map that exists in the database upon starting.
This can be quite annoying when you're working on something across multiple sessions.

**Describe the solution you'd like**
Load the last map that the user has opened up in the editor upon logging in.

**Comment by WeylonSantana** [comment]
@Cheshire92 If possible, could you insert this in the options, instead of being mandatory, a checkbox if possible or something, this is useful in games in production, but maybe not so much when the game is ready, I've seen some people using the first map as the main city or test map precisely because whenever I opened it, it opened on the first map created.

**Comment by Cheshire92** [comment]
I could, but only if / when the other PR that messes with the settings form is accepted.
Don't want to deal with merging two edited forms together.

**Comment by WeylonSantana** [comment]
Alright, no problem, thanks for considering.
