### ISSUE TITLE
Need a solution for long weapon paperdoll rendering.

### ISSUE THREAD

**Issue by Uyarrr** [AscensionGameDev/Intersect-Engine#1074]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/63975845/153722206-7a123131-b6ac-4d63-8b0f-96148b465506.png)

**Additional context**
Right now, if you have 2x2 something in the map example, if you are behind of a tile, it looks bad.

**Comment by jcsnider** [comment]
The bottom half is going to be ground or mask tiles so that you can walk in front.... The best solution available is to block it so you cannot walk behind at all or you cannot walk directly in front and then make it all mask or fringe respectively.

Any sort of rendering magic in which we make a layer pretend to be a mask if the player is below and also act as fringe if the player is above that could be done would come with either a really annoying development experience or a large rendering performance hit or both. None of which I think we should consider at this time.

**Comment by Arufonsu** [comment]
> The bottom half is going to be ground or mask tiles so that you can walk in front.... The best solution available is to block it so you cannot walk behind at all or you cannot walk directly in front and then make it all mask or fringe respectively.

This is pretty much the best you can do with trees / rocks / etc on intersect right now: 
draw the bottom half textures in the mask layer, draw the top half above the player, place a block tile in the top half tile in the case of tall things like trees for example.

Closing this for now since is not really an issue when it comes to mapping right now, and as JC mentioned, working around it may:

> come with either a really annoying development experience or a large rendering performance hit or both. None of which I think we should consider at this time.
