### ISSUE TITLE
bug: Attack While Moving Hides Player

### ISSUE THREAD

**Issue by jessidion** [AscensionGameDev/Intersect-Engine#1086]
**Describe the bug**
Basically I've downloaded and used a fresh 0.7.0.129 install and this has been happening. Whenever I move (any sprite I try) and try to attack while moving the sprite disappears for the duration of the attack. If the character simply attacks while he isn't moving the issue does not occur. I have set _attack _weapon _shoot _cast _idle accordingly and everything looks fine on that part.

**Version Encountered**

0.7.0.129

**To Reproduce**
1. Start moving
2. Attack while moving (press e / lmb)
3. You're invisible for a sec

**Expected behavior**
Play the attack animation without going invisible...

**Screenshots**
https://www.ascensiongamedev.com/resources/filehost/c04f9bf42ba396aa1c5b56c0d82e9ca6.mp4
**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 10

**Additional context**
Is it just me or you guys as well? I tried to go into server settings and disable "Movement While Attacking" but the issue still occurs just a bit more briefly. I really need to fix this as it looks awful breaks the hole game, you can see the paperdolls floating while the player is invisible, any help is appreciated.

**Comment by jessidion** [comment]
I really need to fix this as it looks awful breaks the hole game, any help is appreciated.

**Comment by Arufonsu** [comment]
> 
> I tried to go into server settings and disable "Movement While Attacking" but the issue still occurs just a bit more briefly. 

There's no "Movement While Attacking" variable, but there's the boolean [_AllowCombatMovement_ ](https://github.com/AscensionGameDev/Intersect-Engine/blob/9ac502785d1584917ab584ddb365d4f87727458e/Intersect%20(Core)/Config/PlayerOptions.cs#L52-L55)which has to be **enabled** in order to allow players attack while walking.

Is the weapon slot the same as the shield slot? also, is the amount of frames per animation set up correctly?

**Comment by jessidion** [comment]
> > I tried to go into server settings and disable "Movement While Attacking" but the issue still occurs just a bit more briefly.
> 
> There's no "Movement While Attacking" variable, but there's the boolean [_AllowCombatMovement_ ](https://github.com/AscensionGameDev/Intersect-Engine/blob/9ac502785d1584917ab584ddb365d4f87727458e/Intersect%20(Core)/Config/PlayerOptions.cs#L52-L55)which has to be **enabled** in order to allow players attack while walking.
> 
> Is the weapon slot the same as the shield slot? also, is the amount of frames per animation set up correctly?

That is what I meant ofc and I did not change anything about slots nothing.
Monsters and Npcs don't have this issue and use the same sprite size and frame count than the player sprites :/

**Comment by jessidion** [comment]
Fixed by having the number of "NormalSheetAttackFrame" 1 frame less than "AttackFrames". This is located in the server config.

**Comment by jessidion** [comment]
> Fixed by having the number of "NormalSheetAttackFrame" 1 frame less than "AttackFrames". This is located in the server config.

**Comment by Cheshire92** [comment]
Could you stop closing this?
The fact it allows you to configure incorrectly is a bug that needs to be fixed.

**Comment by Arufonsu** [comment]
> Fixed by having the number of "NormalSheetAttackFrame" 1 frame less than "AttackFrames". 
This is located in the server config.

so, to be clear, the server property's summary says the following:
![imagen](https://user-images.githubusercontent.com/17498701/177058825-f688fe40-8175-4dd9-bd4e-db1d94211b01.png)

Meaning that this property is to select a **single frame** from the normal sheet to use when no _attack sheet has been assigned to that sprite. Thus, if you pick a frame that's outside the index of the normal sheet, you will see no frame at all.

Now, if this is happening while still having _attack sprites and paperdolls, then there's def an issue here that needs to be solved.
![imagen](https://user-images.githubusercontent.com/17498701/177059085-97a69961-1003-4e37-982c-675e48dec235.png)

**Comment by Arufonsu** [comment]
> Fixed by having the number of "NormalSheetAttackFrame" 1 frame less than "AttackFrames". 
This is located in the server config.

So, to be clear, **i don't think that this is an actual issue:** the server property's summary says the following:
![imagen](https://user-images.githubusercontent.com/17498701/177058825-f688fe40-8175-4dd9-bd4e-db1d94211b01.png)

So, this property is meant to select and use a **single frame** from the normal sheet when no _attack sheet has been assigned to that sprite. Thus, **if you set a frame** that's outside of the index boundaries included within **the normal sheet**, you will see no frame at all. In other words, if your normal sheet had up to 5 frames, to say an example, **then you should not set _NormalSheetAttackFrame_ over that value.**

![imagen](https://user-images.githubusercontent.com/17498701/177059085-97a69961-1003-4e37-982c-675e48dec235.png)

Again, i ended up thinking about this report a couple of times, and considering the property's summary and it's outcome, i conclude that **it's behavior is intended to be this way**, and the issues that may arise with it are due to **bad user input** (value bigger than the amount of frames of the normal sheet) and we can't just adjust around everything up when it comes to some bad user input all over the place, I am even more in favor of documenting what this property does in detail than trying to automatically correct erroneous assigned values. thus, I'm closing this one down as not planned for now (unless some maintainer disagrees with this comment/argument).

**Comment by Arufonsu** [comment]
should be resolved by #1674
thus, i'm closing this as complete
