### ISSUE TITLE
feature: Keep the X most valuable items in your inventory uppon death

### ISSUE THREAD

**Issue by da-rulez** [AscensionGameDev/Intersect-Engine#1271]
**Is your feature request related to a problem? Please describe.**
Right now you can set a random chance for items to drop on death but it's too random. You can die and have a chance to lose all your best items, or you can die and only lose your boots.

**Describe the solution you'd like**
Another config option where you can choose items that are certainly kept on death. 
Items kept on death: X -> Here you pick how many items are kept on death
If X = 3 you would keep the 3 most valuable items in your inventory. Value is based on item value from the editor

**Comment by WeylonSantana** [comment]
Which version do you currently use?  because if I remember correctly, you define the drop chance on each item, if you don't want the item to drop, just leave it 0%

**Comment by Arufonsu** [comment]
> **Is your feature request related to a problem? Please describe.** Right now you can set a random chance for items to drop on death but it's too random. You can die and have a chance to lose all your best items, or you can die and only lose your boots.
> 
Pretty sure that is not random like that. Like @WeylonSantana said, the latest version of intersect should include the following:
![imagen](https://user-images.githubusercontent.com/17498701/173125958-98250c38-4e39-41a1-88fe-7ed51b2cd4e5.png)

If this, somehow is not what you are looking for (leaving it at 0% would make it so that specific item never drops), and what you want is a "Keep the X most **valuable** items in your inventory uppon death", i'm sorry to say it but that would pretty much contradict what you see in the previous screenshot and idk if the maintainers / head devs will approve the request in question.

Note: Just changed the title of the feature request to make it more straight to the point.
