### ISSUE TITLE
feature: Rain animation should not be repeated

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1278]
**Is your feature request related to a problem? Please describe.**
Rain animation should not be repeated, this would give a depth effect, making it look like the rain is falling on the ground, not just passing on the player's screen.

**Describe the solution you'd like**
The passing of the rain should die along with the animation and not loop until the particle ends up at the end of the screen.

**Comment by Arufonsu** [comment]
I don't think that the "enhancement" label is the right one for removing a feature in order to replace it with another one 😕 
I like how the rain animation loops and moves around the map as you can set up the X/Y direction and speed for them, removing this feature would be annoying for some devs already using it, including me, i have animated my rain particles so the loop is actually really nice looking and it fits into the logic i've used.

In the other hand, you could do a feature request for an extra toggle (checkbox/bool) that enables rain to work in the way you want it to (which i honestly didn't quite followed, sorry).

**Comment by dudevelopement** [comment]
Yes, a button that allows you to choose between repeating the animation in the animations themselves, would already be good, for both sides.
