### ISSUE TITLE
bug: animation sprites aren't centered on their tiles

### ISSUE THREAD

**Issue by Gorgaki** [AscensionGameDev/Intersect-Engine#1372]
**Describe the bug**
Animation sprites and frames aren't centered on their tiles properly.

**Version Encountered**
7.1.25

**Screenshots**
![image](https://user-images.githubusercontent.com/83343437/178227497-1a4eb548-5fa0-469e-b67d-de318bcca29e.png)
![image](https://user-images.githubusercontent.com/83343437/178226886-b549fd06-ec60-4a97-8fcd-9cd609ce1cfc.png)
![image](https://user-images.githubusercontent.com/83343437/178226945-acffc248-da27-4b37-ae8f-dda9e91077b3.png)

**Comment by jcsnider** [comment]
The animation should be centered in the event tile if no graphic this is caused by WorldPos never being set for the event I think. It worked until Panda simplified entity, label, and hp/cast bars renderings.

**Comment by Arufonsu** [comment]
Just jumped in to check this one and i can verify that this issue is indeed happening, this wasn't an issue prior the latest changes done over entity rendering. Also, **i think that is worth to mention that animations are now rendered under entities no matter what, even with the 'render above player' toggle on** ; Not sure if i should open another issue report for this since i feel like this is related to this as well.

**Comment by Arufonsu** [comment]
Just jumped in to check this one and i can verify that this issue is indeed happening, this wasn't an issue prior the latest changes done over entity rendering.
