### ISSUE TITLE
feature: Party loot distribution / share / pickup information

### ISSUE THREAD

**Issue by naziozeno** [AscensionGameDev/Intersect-Engine#1438]
### Description

1 - A way to change the party loot distribuption.
For example: 
Free for all = the loot will be for who pick up
Random = the loot will be for a random player in party, without discrimination in a ranger of X (edited in config.json)
Leader only = just the party leader can pickup the items

The Loot distribuption will be chosen when creating a party.

2 - A good idea too is to appear in chat who get the item.
For example:
 7 players in a party (at my game the max is 7 members) names: Eu, tu, nos, vos, ele, ela, Vos (member names)
 After kill a boss, it's drop a rare item, at random distribuption, in chat (system or party idk) it will show a message: Vos (party member number 7) got Divine (item name).
 
 3 - At random loot distribuption, the currency got can be shared with all players at same map.
 Example:
 I got 1k gold, theres 3 players in party, the gold shared will be 333 for each.
 
 That's it the party system need a upgrade!

### Intended Use-Case

With this system, the party will be more funtional, with no scams (there many) who got the items and be quiet about that, dont matter if some party members need it more, and ofc be more effective be in a party instead of solo.

### Duplicate Check

- [X] This feature request is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Among the contributors and maintainers of the project, we agreed that we will not work on this feature request, due to the nature of the project, and due to the origin that gave rise to this request, we cannot solve every single problem that emerges due to conflicts between members of a community linked to your project, in fact, the request supposes a feature that only a reduced niche of cases could use, and therefore, escapes the generality that the Intersect Engine intends to cover for the majority of 2D mmos.

You must understand that with every new need that arises in your project, we cannot always be there to provide you with a solution, this kind of situations are precisely the ones that you must solve on your own, especially if you are looking for a solution as complex and specific as the one you have requested.
