### ISSUE TITLE
bug: hotbar description windows position

### ISSUE THREAD

**Issue by RecoStar** [AscensionGameDev/Intersect-Engine#1784]
### Description

Changing the "HotbarWindow" allignment to center bottom of the screen causes the center hotbars to flicker when hovering over to see description box. Normally when hovering the mouse over a hotbar slot, anywhere in within the icon, the description stays up. However while moving the mouse around the icon within the hotbar slot, the description window now flickers.

Only seems to be affecting central slots: HotbarContainer2 to HotbarContainer8

Moving the HotbarWindow to anywhere along the Bottom of the screen (center, right or left) does the same thing. 
Moving HotbarWindow back to top of screen, then issue does not happen.

### Steps to Reproduce

1. Open GUI > Layouts > HotbarWindow.json
2. Change line 8: "Alignments": "Top,Right" to "Alignments": "CenterH,Bottom",
3. Open Client and hover over hotbar slots (need to be populated with items)

Note: Only central hotbar slots seem to be affected: HotbarContainer2 to HotbarContainer8

### Version with bug

v0.7.1.120

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

No, but testing I changed the size of the overall hotbar and moving slots around I found that only center slots are affected.

### Relevant log output

```shell
Nothing
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
this is because hotbar hovering descriptions are currently hardcoded to be under the hotbar itself, regardless of where the hotbar is positioned, sadly. in order to fix this, we need to address this issue along with other issues related to items descriptions.

i had developed something that solved this issue on hotbars, inventory, or on anything that used description windows on hover, it manages to handle them and position them in a way that the flickering never happens again, the PR is unfinished and i sort of gave up on it (for _now_), feel free to give it a try for now: https://github.com/AscensionGameDev/Intersect-Engine/pull/1650
