### ISSUE TITLE
bug: No information about the item we are crafting

### ISSUE THREAD

**Issue by cydyn** [AscensionGameDev/Intersect-Engine#1987]
### Description

When we create a diagram of a crafting item such as a weapon, shield, armor, etc., and put it in the crafting menu, then enter the game and try to make it, the top where the item is shown does not have these basic statistics. only shows hp, mp, cdr

### Steps to Reproduce

1.Make a crafting item such as a weapon or shield
2. Add an item to the crafting menu
3. go into the game and run this crafting menu
4. in the corner, where you can see the item we want to craft, no basic statistics such as attack, defense or speed are visible at all ( bug )

### Version with bug

0.8.x

### Last version that worked well

I dont know

### Affected platforms

Windows

### Did you find any workaround?

Nope

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by EspectroW94** [comment]
I have the same problem, since version 7.2.xx

look at this equipped item:
![Captura de pantalla 2023-10-17 231927](https://github.com/AscensionGameDev/Intersect-Engine/assets/127634629/93fa294b-7f44-4bed-91b7-9e00d7c72226)

now look at the exact same item in the crafting window:
![Captura de pantalla 2023-10-17 232028](https://github.com/AscensionGameDev/Intersect-Engine/assets/127634629/231e392d-c24e-45f6-8680-59c404c318f1)

I think it is a problem in the gamedata.db since if you create a new server, from 0 and use your old database, the error occurs.
Otherwise, if you use a new gamedata.db in your project and create a craft, the problem disappears.

**Comment by cydyn** [comment]
Just wondering if it can be fixed now. Since the new gamedata does not cause the error and migration did. we won't delete the gamedata file now because everything will be lost.
I checked version 0.7.65 and this problem actually occurs. however, the last backup from this version also has this error
