### ISSUE TITLE
bug: projectiles cannot be fired leftwards on a map border

### ISSUE THREAD

**Issue by Mcadams** [AscensionGameDev/Intersect-Engine#2195]
### Description

If you are on the border between two maps, you cannot fire a projectile to the left. Any other direction works, and if you cross over the border, you can fire a projectile over it to the right, but from the left does not work.

https://streamable.com/x0yym1

### Steps to Reproduce

1. Attempt to fire a projectile to the left at a map border
2. Nothing happens

### Version with bug

v8.0.136

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

No

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
_probably related?_ : #1912

**Comment by Arufonsu** [comment]
Did some research on this today, here are some of my tests:

by default maps have (0+31x0+25) tiles `("MapWidth": 32, "MapHeight": 26)` (x,y) 
- if i shot from 0,0 to the left map: projectiles goes to next map fine
- if i shot from 0,25 to the left map: projectiles does not go to next map (bug)
- if i shot diagonally from 31,0 to the right map: projectiles does not go to next map (bug)
- if i shot diagonally from 0,25 to the left map: projectiles doesn't not go to next map (bug)


The issue seems to be related to the way we're checking the boundaries of the map. We're using `Math.Round(newx)` and `Math.Round(newy)` to determine if the projectile has hit the edge of the map. This could cause issues if the projectile's `x` or `y` position is exactly at the edge of the map, because `Math.Round()` rounds to the nearest integer, which could be either inside or outside the map depending on the exact floating point value...
