### ISSUE TITLE
bug: clear target when taunted

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#2253]
### Description

When we are under the taunt effect, we cannot select other targets, ok, but we can remove the target, which is wrong

### Steps to Reproduce

need a check here

https://github.com/AscensionGameDev/Intersect-Engine/blob/4eff95eca51bb98aac144c2ba0f08cd408e8c3f1/Intersect.Client/Entities/Player.cs#L2045

### Version with bug

current

### Last version that worked well

Unknown

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
> but we can remove the target

and doing so lead to some kind of exploit or ... ? 
please explain further, what's the actual bug?

**Comment by WeylonSantana** [comment]
> > but we can remove the target
> 
> and doing so lead to some kind of exploit or ... ? please explain further, what's the actual bug? _(you have provided the current behavior, but what is the expected one?)_

the taunt's effect should force its target to be just the caster, removing the target shouldn't be an option.
we can remove the target when we are under the effect of taunt, but it shouldn't

It's not an exploit, it's just a detail

**Comment by Arufonsu** [comment]
Okay, gave this a try, for the next time please, try to be more specific on how to reproduce, so this is how to reproduce:

- Expected behavior: taunt's effect forces its target to be the caster, removing the target shouldn't be possible.
- Current-not-expected behavior: pressing the esc / menu key clears the current target while taunted.

Found a way around it, will post a PR for it 👍🏽 please give it a review when is up @WeylonSantana
