### ISSUE TITLE
Some way to protect the /resources/ folder from theft of content.

### ISSUE THREAD

**Issue by ThousandX** [AscensionGameDev/Intersect-Engine#249]
**Is your feature request related to a problem? Please describe.**
I was analyzing it, and I would like to know if it is possible for the engine to be able to read the / resources / folder from within a .zip folder with a protected password. As for example the game Ragnarok Online or even tibia, tibia uses a .dat extension with all files inside, and Ragnarok with a .GRF extension. Therefore, these files can be opened only by the responsible company.

**Describe the solution you'd like**
Some way to compress the files by the game's own editor, like the image packs system, but rather all files.
When clicking on the button (Pack Game Files) it will create an .agd file where only the game client will be able to read. I imagine that it is complex to make such a system, but it could be a .zip compression, this will protect the files not only from theft, but also from modifications.

**Additional context**
This would take the engine to another level

**Comment by jcsnider** [comment]
Our current stance (subject to change down the line) is that any sort of asset protection should be done on a per-project basis and would not fit in the base engine.

This is supported by the fact that there is no method of protection that we could program and release open source that couldn't be reverse engineered with ease which would leave all projects open to having their assets stolen.

**We do not want to provide a feature that gives users a false sense of security.**

There are some really basic steps we could take in order to make stealing assets slightly harder. For example allowing the renaming of file extensions, or compressing the files in a gzip stream of some type. We may revisit that down the road.
