### ISSUE TITLE
Delete Character

### ISSUE THREAD

**Issue by fugakuar** [AscensionGameDev/Intersect-Engine#434]
**Describe the bug**
The character when attacked does not disappear if it is deleted from the panel.

**Version Encountered**
0.6.2.0

**To Reproduce**
1. Go to fight with any npc
2. Press ESC and go to character while you're in battle
3. Quickly you give to delete character. You create a new one and enter the game
4. The character does not disappear until the NPC stops attacking him, kills him or someone kills the NPC.

**Expected behavior**
My expected behavior is that the character is automatically deleted.

**Screenshots**
https://www.youtube.com/watch?v=kPDXC_UUWe8

**Logs**
N/A

**Operating System:**
Windows

**Additional context**
The fact that the character does not disappear in battle is fine, but what if this character is a level higher than the npc? The character will never disappear. If an NPC is in the spawn zone and the character dies again and again, he will not be eliminated either.

**Comment by Arufonsu** [comment]
>     1. Go to fight with any npc
> 
>     2. Press ESC and go to character while you're in battle

imo, there should be a check so players are not able to log off / swap into the character selection screen during a battle for a specific period of time, lets say, 1 minute, this way no one could abuse this.


> **Expected behavior**
> My expected behavior is that the character is automatically deleted.

if the check that i'm suggesting its ever implemented, an "already logged in" check should also be implemented along with this, that way, if the account holder tries to delete the character while this character its still in game/battle and unable to log off, the account holder should receive a "you can't delete a character that's already logged in" warning notice instead of simply delete it...
