### ISSUE TITLE
Chat bubbles addition to to 'show text' command

### ISSUE THREAD

**Issue by da-rulez** [AscensionGameDev/Intersect-Engine#483]
When you want to show a text you can pick between a dialogue box or a chat box text. I propose an extra solution and that's a chat bubble that you can place above the player or the event.

**Comment by Arufonsu** [comment]
This is a neat idea, reminds me of mighty and epic online games like Tibia, where you (originally) had to speak with NPCs though the chat log/box dialogues, lets say, instead of interact with an NPC with actions/buttons, you would have to interact with NPCs using actual dialogues which can be recognized by the NPC's AI. 

ie:

Player: "Hi"
NPC: "Oh! welcome back <PlayerName>! What can i do for you today?"
Player: "i want to **buy** something!"
NPC: "Please Take a look on our current stock!" (opens a shop UI)
