### ISSUE TITLE
You are able to set multiple hotbar slots to one key

### ISSUE THREAD

**Issue by da-rulez** [AscensionGameDev/Intersect-Engine#485]
There should be a check in place to see if a key is already assigned to something.

**Comment by jcsnider** [comment]
Is it really that hard to fill in a template? Even if the bug is simple having notes on what version the bug applies to will help for future reference.

**Describe the bug**
You are able to set multiple hotbar slots to one key there should be a check in place to see if a key is already assigned to something.

**Version Encountered**
0.7.0.106 (and all versions before)

**To Reproduce**
Kinda obvious but try to assign the 1 key to multiple hotbar slots or controls in general.

**Expected behavior**
If you try to assign a key to two different controls remove the key from the original action.

**Screenshots**
![](https://www.ascensiongamedev.com/resources/filehost/1007bd64ac7f6248e5b974d8511662fa.png)

**Operating System:**
Windows, Mac, and Linux
