### ISSUE TITLE
Error connecting client to prerelase version on ubuntu server.

### ISSUE THREAD

**Issue by blinkuz** [AscensionGameDev/Intersect-Engine#545]
**Describe the bug**
As the title says when trying to connect a client to the server running version 106 of the prelease I am having this error, I have checked the log and there is nothing registered about it.
I have also done tests locally and everything works perfectly, I don't know if it is a problem with the installation of mono on the server or that it is ignoring something.

The server is an Ubuntu 18.4 LTS and I can run version 102 of the prelease without problems.

**Version Encountered**
7.106

**To Reproduce**
1. Compile latest changes in release mode.
2. Upload it to the server and put it online.
3. Connect a client.

**Expected behavior**
It should not crash when connecting a client, as it works locally.

**Screenshots**
https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/f5101408f3c184929b420628f687937d.png

**Operating System:**
Linux

**Comment by Arufonsu** [comment]
Not quite sure how mono handle things, but:

` condition 'ins->opcode > MONO_CEE_LAST' not met `
indicates that this might be related with Assertion in mono, from the source code of mono i found this:
https://github.com/mono/mono/blob/master/mono/mini/method-to-ir.c#L12307

Eveything seems to happen in the Intersect.Network project within the solution.

Maybe you could help the devs by providing some extra info, like: which VS version you used in order to compile the solution, if you cleant the solution before building in order to allow the compiler to update all the Nuget packages.

Hopefully this information can lead devs to find the solution, im interested in hosting the server in a headless Linux distro as well <3

**Comment by blinkuz** [comment]
I am using VS 2019 Community to compile and I have cleaned the solution before compiling, on the mono version it was 4.6.2 which is a bit old, now I have updated it and I am getting this error even in the versions that previously worked.

https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/4f65613347715b91b0a09374ec32c673.png

**Comment by blinkuz** [comment]
I have been able to solve the problem, I have updated to Mono 6.12 but I got a new error, the solution was to install an intermediate version which was Mono 6.6 and everything runs perfectly.
