### ISSUE TITLE
Source Name

### ISSUE THREAD

**Issue by TalesOfOracle** [AscensionGameDev/Intersect-Engine#69]
Hello,
        Only seems fitting to put this here in Bug report, except its not actually a bug. I'm trying to centralize the source, to make everything in the name of my game. For example "Intersect Core.dll" to "Tales of The Oracle.dll" or "Intersect.Network.dll" to "Tales of The Oracle.Networking.dll". Im familiar with how VS works and went through everything but the end result when everything compiles correctly, the client gives me an error, and when I look in the error file its related to "Networking" specifically the "Crypto" modules. Something about trying to read past the end of stream. Does everything need to say "Intersect" or am I doing something wrong or is there a system in place to prevent the source name change?

**Comment by jcsnider** [comment]
This isn't a bug and should be discussed on the forums here:
https://www.ascensiongamedev.com/forum/372-development-questions/

At the end of the day we have to reference a lot of our libraries through reflection in order to export dlls and such that are compiled within our .exes and libraries. By renaming the libraries you are breaking those reflection calls.

You can still get it to work, but you'd need to dive very far into the code looking for Intersect.* references and changing them.  Given how Costura/Fody packages all those dlls into the client so they are never seen anyways I don't think you get any value for all the work involved.

**Comment by TalesOfOracle** [comment]
Thanks so much! I don't know if its my OCD talkin, but I just like everything being centralized.

**Comment by jcsnider** [comment]
You're OCD should submit to the fact that if you change everything.. and you try to keep up with our updates/bug fixes you will very likely end up with tons of merge conflicts and tons of extra work constantly. It's not worth it lol
