### ISSUE TITLE
(video) Can't upgrade my game from 6.1 to 7.0

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#734]
**Describe the bug**
I can't upgrade my game to version 7.0 and I was asked to make a video and post it here so I could get any help.

**Version Encountered**

My game is in version 0.6.1.261
I'm trying to upgrade to 0.7.0.120 but command prompt simply closes after :|

**To Reproduce**
Check video I uploaded showing process
https://streamable.com/nyprsw

**Logs**

**Operating System:**
Windows

[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6489229/errors-Intersect.Server.log)
[Intersect Server-2021_05_16-14_44_59_416.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6489230/Intersect.Server-2021_05_16-14_44_59_416.log)
[Intersect Server-2021_05_16-14_46_14_619.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6489231/Intersect.Server-2021_05_16-14_46_14_619.log)
[Intersect Server-2021_05_16-14_46_40_439.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6489232/Intersect.Server-2021_05_16-14_46_40_439.log)

**Comment by jcsnider** [comment]
Zip up your server folder (including databases) and send to me via a PM on AGD.

**Comment by jcsnider** [comment]
Caused by having multiple player or server variables with identical Text Ids... which made these functions crash upon launch:
https://github.com/AscensionGameDev/Intersect-Engine/blob/82d5858a7bb84990dee671ba9a3bc7c83bef55d4/Intersect.Server/Database/DbInterface.cs#L1198

https://github.com/AscensionGameDev/Intersect-Engine/blob/82d5858a7bb84990dee671ba9a3bc7c83bef55d4/Intersect.Server/Database/DbInterface.cs#L1212

Removing the duplicated text ids before upgrading will solve the problem. I will create a PR so that even if text ids are duplicated the server won't crash in the future.
