### ISSUE TITLE
Blocked on the animations give little regrowth

### ISSUE THREAD

**Issue by TalikanPDMO** [AscensionGameDev/Intersect-Engine#817]
Hi,

**Describe the bug**
If you add an animation with the "block tile" there is a regrowth

**Version Encountered**
7.0.121

**To Reproduce**
Create a animation with block tile like this : 
![bug 1](https://user-images.githubusercontent.com/25484642/124345285-4a3f1880-dbd8-11eb-8c34-38ef3266ff16.png)

**Screenshots**
![Bug](https://user-images.githubusercontent.com/25484642/124345290-53c88080-dbd8-11eb-8ec2-22899c3b9b5e.gif)

**Logs**
no log

**Operating System:**
Windows 10

**Additional context**
/

**Comment by jcsnider** [comment]
Can you please confirm that this exists in a clean copy of 0.7.0.121 with no source modifications?

**Comment by Arufonsu** [comment]
i can confirm that its been going on since i knew/tried animations for the first time, i honestly though that "blocked animation tiles" simply worked differently from the regular block atributed tiles.
if by "regrowth" he means this bouncy like effect shown in the gif, then yeah, this has been the behaviour of them as since i know them.

**Comment by jcsnider** [comment]
Copy that. I thought I had fixed that already once or twice, but it could have been in private projects. It'll be a quick and easy fix.

**Comment by Arufonsu** [comment]
Just to confirm:

![imagen](https://user-images.githubusercontent.com/17498701/124345686-662ac600-dba8-11eb-92aa-3c6235553da0.png)


https://user-images.githubusercontent.com/17498701/124345676-5f03b800-dba8-11eb-9f33-be58a031435b.mp4
