### ISSUE TITLE
Event Instantiation and Removal (XReq #4)

### ISSUE THREAD

**Issue by Xyseer764** [AscensionGameDev/Intersect-Engine#853]
**Is your feature request related to a problem? Please describe.**
Modifying the game-world is currently impossible from the server. This severely limits the options in the engine. While I'd love to see the ability to edit all aspects of the world from Event commands, I realize it's out of scope for this project. But introducing even just Event instantiation and removal would multiply the amount of options the developer has. Currently any system that wants to dynamically change the world (not from pre-placed conditional events) is impossible to implement from the editor.

An example of this would be the placement of player-generated content such. Currently players have no dynamic way of affecting the world and pre-placing every event is not scalable beyond debug purposes.

**Describe the solution you'd like**

- Template Events
`This would be a tab similar to common events, except that I'd inherit all of the functionality map-events posses (sprite, facing ect)..`
- Spawn Event Command in events
`This command would take an Event input (from Event Templates) and a position input. Preferably it'd have 3 settings on how to spawn the event: 1. Spawn it there no matter what, removing any event that might've been there; 2. Spawn it as close as possible to the target position if it's blocked; 3. Don't spawn the event if the position's already occupied by another event.`
- Remove Event Command in events
`If spawning events becomes possible, adding functionality to remove them will also be mandatory. It'd just be a simple argumentless command that destroys the event it's used in.`

**Additional context**
I recognize this requires a decent amount of dev time, but it's a major feature that'd add generalized functionality to the Engine. Any project that wants to have a dynamically changing world will benefit from this feature - and I'm guessing most developers would like to have at least SOME dynamic world changing in their game.

**Personal Note**
I've discovered the engine recently and I'm examining its functionality for my project. I come from a Unity/Godot environment, but my plan to make an MMO made me go looking for alternatives better than just coding the entire thing myself (from my experiences, I really hate dealing with net code). I'm impressed with the engine's back-end as it handles all of the networking bull-crap I didn't want to deal with. Unfortunately, every time I try to implement something using the editor, I find it extremely lacking in basic functionality, which is why I'll be creating a few feature suggestions which I think would massively improve the engine's functionality and are really general to the entire MMORPG experience. I want to contribute to the project in the future, but the lackluster (most of the time completely absent) use of comments in the code and no code documentation multiply the amount of time I'll need to grasp the code base a hundred-fold.

**Comment by jcsnider** [comment]
This comes back to the point where you really don't want hundreds or thousands of events running all the time because they are not very efficient... if used rarely this wouldn't be bad... but then the preconditioned events would probably be fine. If used in dozens or hundreds of instances then you should have a custom, hard coded solution for whatever dynamic effects you are trying to create.

**Comment by Xyseer764** [comment]
I might not be understanding the network architecture of the engine then, because I thought having 1000+ events on the map was expected with a large game. Would allowing the player create Events that work like walls/doors/chests/planted seeds slow down the game that much?

Maybe I worded the suggestion poorly, but what I meant wasn't to suggest something like creating events that constantly run (already have that covered with common events), but events that can exist in the world. The instantiation would happen completely on the server-side, with the player simply being ably to trigger it.

I understand that doing stuff through events might be slow, but this isn't even about enabling us to calculate more stuff, rather allowing us to customize the world mid-session dynamically through event commands instead from the editor.

**Comment by jcsnider** [comment]
Events exist individually for each player so the event count is events * players on any given area (which is 9 maps, the one the player is on, and the 8 that surrounds them). Events are always trying to spawn/despawn based on their given conditions, and they are all updating to run commands, process movement, every server tick.

So the more events you have, the most work the server must do each tick. Once each tick reaches a certain execution time 30ms+ projectiles and such will be noticeably delayed. Once that time exceeds 100ms the whole game will feel laggy to players.

When you have 1 player online you can create insanely inefficient events to achieve your goals. When you have 200+ players online those events can end up severely hurting performance.

So if you goal is to have a farmable area, say 10x10 tiles. You should NOT have 100 events. Instead you should have a hard coded Soil map attribute that accomplishes the same task with minimal overhead instead of events with higher overhead.

Events are tailored for dialogue npcs, warping, shop keepers, puzzles, etc. They are not meant for creating wide spread game features.

**Comment by Xyseer764** [comment]
What if I were talking only about global events? That's what I had in mind anyway, so not allowing that functionality as to not grind the server to a halt seems fine to me.

>  Events are always trying to spawn/despawn based on their given conditions

Even if they have no condition lists?

> updating to run commands

Even when the event is not currently running? Aren't event commands triggered by having a signal sent to trigger them? If so then you're speaking only about autorun events, which obviously are not performant.

> process movement

Even events that do not have any movement?

> Events are tailored for dialogue npcs, warping, shop keepers, puzzles, etc. They are not meant for creating wide spread game features.

I think they could be, though. There isn't some inherent quality to "Events" that makes them extremely computation-intensive. An event that has no movment, no conditions, only one page and is activated on player interaction (and is global) should have the same load on the server as a resource. The rub is, that events allow for much more options.

**Comment by jcsnider** [comment]
Global events only sync the event locations among players. They still technically are separate entities are far as the server is concerned because for a global event one page might be spawned for one player and another page might be spawned for another.

If you have events that are doing nothing then obviously there won't be much, if any, of a performance hit.

We've seen a lot of projects use events to create massive systems which they were never intended for, which has harmed performance. These feature requests, while nice to have, would further encourage, or otherwise make those sorts of systems easier to implement. (When they otherwise should still be source edits, even if that's more challenging.)

Before implementing features like this, I want to hone in on specific viable use cases to justify the implementation effort, and long term upkeep of the system. I see this request specifically as a lot of upfront dev, lots of work to upkeep over time, very few use cases where this would be helpful, and a ton of opportunity for people to over use it and unintentionally hinder performance.

**Comment by Xyseer764** [comment]
So with what you said, to me it seems that a properly implemented farming system would be as performant when being implemented from events as it'd be if it were implemented from attributes. Tell me if this would be slower:

1. You have the first object, that is the seed. It's completely empty other than the sprite and a wait command + a command to spawn an event on its tile and then remove itself
2. The second object is a pickable fruit that's empty except for the fact that it grants resources to the player and removes itself after that.

To me it seems that the events aren't making any major unnecessary calls and if I were to program the attribute in, I'd also have to deal with computing the same things.

The use case would be for systems like the one I mentioned above. Anything related to player-created and player-changed environments would become possible out of the box and I don't think that being afraid of incompetents mass-spawning monster events should be a deterrent to implementing the system.

**Comment by jcsnider** [comment]
Given the above example I don't see how you can't have 2 pages in one event. Page one is the empty soil which takes the seed and then waits Xms and finally sets an event switch to true. That event switch being true would be the condition for the second page which shows the grown plant for harvesting, and once harvested the switch gets set back to false and the original page displays (empty soil). 

The problem you would face is that event switches do not persist in the db (which would be a really cool feature request and PR) so once a player leaves the area that value is lost and the crop will revert. Meaning that you would need a separate global or player variable for every single plot of land that you can grow something on.

If done as a custom system you could have a db table which automatically tracks the map id, x/y coordinate, crop and growth timer of each seed that persists across server reboots. You would then keep your variable list clean.  Furthermore you could have those seeds update every 100 ticks or even less frequent whereas events would be processing every single tick.  And packets that send graphic data/information about those tiles would be far less than the data that is sent for an event page which contains information like event names, sprite directions, movement speeds, etc.

**Comment by Xyseer764** [comment]
> Given the above example I don't see how you can't have 2 pages in one event. Page one is the empty soil which takes the seed and then waits Xms and finally sets an event switch to true. That event switch being true would be the condition for the second page which shows the grown plant for harvesting, and once harvested the switch gets set back to false and the original page displays (empty soil).

I outlined this implementation in particular, because it removes the need for checking the condition of the event (if the event has no conditions, I hope it doesn't check for them).

>  And packets that send graphic data/information about those tiles would be far less than the data that is sent for an event page which contains information like event names, sprite directions, movement speeds, etc.

Wait, is the server sending packets of the entire event every tick? I thought it sent the event once when it comes into the view of the client and then sends update if the event changes in some way. Sending over an entire event every tick seems really inefficient.

Welp, I guess this request is going nowhere then. What I was mainly aiming for with this feature suggestion was to give us a way for player-made environments, as it's a feature that'd be useful in just about any project, but I guess I'll have to try and implement it myself.

**Comment by jcsnider** [comment]
> I outlined this implementation in particular, because it removes the need for checking the condition of the event (if the event has no conditions, I hope it doesn't check for them).

The processing difference is negligible. Either it's going to try to process commands, check the wait timer, and then abort which is no more time consuming then checking if a single condition is true/false in which the page should switch over.

> Wait, is the server sending packets of the entire event every tick? I thought it sent the event once when it comes into the view of the client and then sends update data if the event changes in some way. Sending over an entire event every tick seems really inefficient.

No.

 > Welp, I guess this request is going nowhere then. What I was mainly aiming for with this feature suggestion was to give us a way for player-made environments, as it's a feature that'd be useful in just about any project, but I guess I'll have to try and implement it myself.

It probably isn't - the request is simply outside the bounds of what events are meant for. Events can still work for limited use cases, such as helping a npc repair their house where the graphic switches over after a quest completes or something. Anything more widespread than that should have a dedicated system. A dedicated system can update/process on the server less frequently, appropriately store metadata in the database which will persist across reboots, and render on the tilemap cached within the vbos so you have fewer overall drawing calls and higher client fps/performance.
