### ISSUE TITLE
Critical color rendering doesn't work

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#925]
**Describe the bug**
I want the critic to be yellow, regardless of the type of damage

**Version Encountered**
0.7.0.126

**To Reproduce**
1. 
![image](https://user-images.githubusercontent.com/63019821/131128742-dde98fea-4fd9-4815-a7f4-47d75ca24001.png)

2. 
![image](https://user-images.githubusercontent.com/63019821/131128809-5ae2f454-575b-4bde-97dd-866bc60fbae0.png)

3. 
Normal Damage: 
![image](https://user-images.githubusercontent.com/63019821/131129088-63fffc0d-5547-43b2-833f-2309e64c9938.png)
Critical Damage: 
![image](https://user-images.githubusercontent.com/63019821/131128861-55c89bf6-015c-46e6-b08e-2e1d7bc97e4d.png)

**Expected behavior**
Critical hit rendering in defined color

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by Arufonsu** [comment]
doesn't critical hits display an uppercase "CRITICAL HIT!" Combat type message instead of the damage itself?
i'm pretty sure that you may change the font colour of such string message only.

Not sure if i can reproduce this, the bug i see here is "CRITICAL HIT!" not being displayed instead.

...
In the other hand, i would personally like this to be an optional feature (display "CRITICAL HIT!"  vs  Actual dmg ) along with the ability to set a different font style for critical hits, that would be awesome imo >.<

**Comment by WeylonSantana** [comment]
I'm really stupid, I don't know what happened with me lol I removed the critical string because I wanted to be able to see the damage, the word critical is always on top of the damage, and I don't want to keep calculating the damage always in the calculator, because some reason in the universe i thought that line was for the damage color and i forgot it was for the string haha i must be in love to make a silly mistake like that.
thanks for the light again @Arufonsu

**Comment by Arufonsu** [comment]
Yeahh, not a bug, but i like the idea (i removed the critical hit string for the actual damage output as well), perhaps, starting a **feature enchancement** issue discussion related to this would be nice, like i previously said, it might be awesome to have the ability to pick whether the output of critical hits is the string or the actual damage, along with a different font and colour for them.
